

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: taskapp
      POSTGRES_USER: task
      POSTGRES_PASSWORD: ${DB_PASSWORD:-devpw}
    volumes:
      - /srv/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskapp
      SPRING_DATASOURCE_USERNAME: task
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-devpw}
      FOLDERPICKER_BASE_PATH: /data/files
      ATTACHMENTS_BASE_PATH: /data/files/attachments
    volumes:
      - /srv/taskapp/files/share1:/data/files
      - /srv/taskapp/files/attachments:/data/files/attachments
    ports:
      - "8080:8080"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/fs/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 25s	
    restart: unless-stopped

  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./frontend/dist:/srv/frontend:ro
    depends_on:
      - backend
    restart: unless-stopped
