# version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: taskapp-db
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [appnet]

  backend:
    build: ./backend
    container_name: taskapp-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskdb
      SPRING_DATASOURCE_USERNAME: taskuser
      SPRING_DATASOURCE_PASSWORD: taskpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"   # wichtig bei „gebrauchten“ Schemas ohne History
      #SPRING_PROFILES_ACTIVE: docker
      SPRING_PROFILES_ACTIVE: prod
      APP_CORS_ALLOWED_ORIGINS: "http://nb01:8081,http://nb01:5173,http://192.168.178.23:8081,http://192.168.178.23:5173,http://localhost:8081,http://localhost:5173,http://master-pc:8081"
      ATTACHMENTS_BASE_PATH: /data/attachments
      TZ: Europe/Berlin

    volumes:
      - ./data/attachments:/data/attachments

    ports:
      - "8080:8080"
    networks: [appnet]

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE: ""
    container_name: taskapp-frontend
    depends_on:
      - backend
    ports:
      - "8081:80"
    networks: [appnet]

volumes:
  pgdata:

networks:
  appnet:
    driver: bridge