-- Version-Column für Optimistic Locking (Spring @Version)

CREATE TABLE attachments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL,
  filename VARCHAR(255) NOT NULL,
  mime VARCHAR(255) NOT NULL,
  size BIGINT NOT NULL,
  storage_key VARCHAR(200) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_att_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
);