spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/taskapp
    username: task
    password: devpw
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
folderpicker:
  base-path: "C:/Users/Master/task-app/files"
attachments:
  base-path: "C:/Users/Master/task-app/files/attachments"
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/taskapp
    username: task
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
folderpicker:
  base-path: ${FOLDERPICKER_BASE_PATH:/data/files}
attachments:
  base-path: ${ATTACHMENTS_BASE_PATH:/data/files/attachments}
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://db:5432/taskapp
    username: task
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
folderpicker:
  base-path: ${FOLDERPICKER_BASE_PATH:/data/files}
attachments:
  base-path: ${ATTACHMENTS_BASE_PATH:/data/files/attachments}
server:
  port: 8080
